dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "ZqBvWsBgfvf8Vly+o88qYp5VS2vkBhX8tazf0rVTo2+eXEY0Lz5yKHHe9YpNYo6DvqDe960MlziALM/9paP09gdC5X/0Qa6edRmDShpX8SZ8LsmGuXW19CwdXdIgNWVLaw6CuEVwaPP2kJh3I2zypxbdU89Y/UV2bGIxML7FxYdzfWqA7ECRTqmPGY+Tb6Z7ynmjYZarTXhVkoDd9LZn40vLSyfy5ZzDo6pLQctuLRo34drNKUR0hJHtdWIegLt79zDB8Z5fga802VdCOkkDsIPZ9fIv/JQh35+BQIOsqm8Q5d6d5jTG4JpS8rMHA0sQUC1YVQl2LI8uuSL7MTMO3+/kZ43mCFdtnrsKHYFU368ewoLn+rH9Pk20Q0pmy7S0kofv0PEqoORVCteOLeySjZwp9V9hnN5+zojd/3TDs5/ExjUrO7RgOiEMXld58Z6BdBf/FaW6zrbnFSx6x61fkn+fTT3I0bhKeSdAEIk79Awvo++EsCzUN7sUBM5z82UkAwNgTCi1pTelecSQTV7HhbPKqXBvpeZtLqCCgKizXy0BF7AdA1ctDWkJ2poDr7+IVmy//WfgH1h7YbHbwNb1YiSKSG+gv23gAx7dEciVSW5/nEU1l9LSDHzyWjDWJ+zJcWo1OxFQ0tGngRWnn6cCbfeZn0+vQC37+XOYLdGQpMA="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
